config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root "press_releases#index"

  resources :organizations
  resources :publishers
  resources :press_releases
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :publishers
  has_many :press_releases, through: :publishers

  validates :name, presence: true, uniqueness: true

  before_destroy :check_for_publishers

  private
  def check_for_publishers
    if publishers.any?
      errors.add(:base, "Cannot delete organization with associated publishers.")
      throw(:abort)
    end
  end

end

app/models/press_release.rb
class PressRelease < ApplicationRecord
  require 'active_support/core_ext/numeric/time'

  enum status: { draft: 0, published: 1, archived: 2 }

  validates :title, presence: true
  validates :content, presence: true
  validates :publisher_id, presence: true
  validates :user_id, presence: true
  validate :validate_publish_date_in_future

  belongs_to :publisher
  has_one :organization, through: :publisher
  belongs_to :author, class_name: "User", foreign_key: "user_id"

  after_create :schedule_publish_press_release_job

  private
  
  def validate_publish_date_in_future
    if publish_date.blank?
      errors.add(:publish_date, "can't be blank")
    elsif publish_date < Time.now
      errors.add(:publish_date, "can't be in the past")
    elsif publish_date < Time.now + 4.9.hours
      errors.add(:publish_date, "should be at least 5 hours ahead of the current time.")
    end
  end

  def schedule_publish_press_release_job
    PublishPressReleaseJob.set(wait_until: publish_date).perform_later(id)
  end
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  belongs_to :organization
  has_many :press_releases, dependent: :destroy

  validates :name, presence: true, uniqueness: { scope: :organization_id }
  validates :organization_id, presence: true
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Assuming a user can author many press releases
  has_many :press_releases, foreign_key: "user_id"
 
  def has_role?(role_name)
    roles.where(name: role_name).any?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: %i[ show edit update destroy ]

  def index
    @organizations = Organization.all
  end

  def show
  end

  def new
    @organization = Organization.new
  end

  def edit
  end

  def create
    @organization = Organization.new(organization_params)
    if @organization.save
      redirect_to organization_url(@organization), notice: "Organization was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @organization.update(organization_params)
      redirect_to organization_url(@organization), notice: "Organization was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @organization.destroy
      redirect_to organizations_url, notice: 'Organization was successfully destroyed.'
    else
      render :show, status: :unprocessable_entity, location: @organization
      # redirect_to @organization, alert: @organization.errors.full_messages.to_sentence
    end
  end

  private
    def set_organization
      @organization = Organization.find(params[:id])
    end

    def organization_params
      params.require(:organization).permit(:name, :description)
    end
end

app/controllers/press_releases_controller.rb
class PressReleasesController < ApplicationController
  before_action :set_press_release, only: %i[ show edit update destroy ]

  def index
    # Assuming `status` is a parameter that comes from the UI for filtering
    @press_releases = if params[:status].present?
                        PressRelease.where(status: params[:status])
                      else
                        PressRelease.where(status: 'published')
                      end
  
    # Respond to Turbo Stream to allow dynamic updates
    respond_to do |format|
      format.html # For initial page load
      format.turbo_stream # For dynamic updates without page reload
    end
  end

  def show
  end

  def new
    @press_release = PressRelease.new
  end

  def edit
  end

  def create
    @press_release = PressRelease.new(press_release_params)
    if @press_release.save
      redirect_to press_release_url(@press_release), notice: "Press release was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @press_release.update(press_release_params)
      redirect_to press_release_url(@press_release), notice: "Press release was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  def destroy
    @press_release.destroy!
    redirect_to press_releases_url, notice: "Press release was successfully destroyed."
  end

  private
  def set_press_release
    @press_release = PressRelease.find(params[:id])
  end

  def press_release_params
    params.require(:press_release).permit(:title, :content, :publish_date, :status, :user_id, :publisher_id)
  end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  before_action :set_publisher, only: %i[ show edit update destroy ]

  def index
    @publishers = Publisher.all
  end

  def show
  end

  def new
    @publisher = Publisher.new
  end

  def edit
  end

  def create
    @publisher = Publisher.new(publisher_params)
    if @publisher.save
      redirect_to publisher_url(@publisher), notice: "Publisher was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @publisher.update(publisher_params)
      redirect_to publisher_url(@publisher), notice: "Publisher was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @publisher.destroy!
    redirect_to publishers_url, notice: "Publisher was successfully destroyed."
  end

  private
    def set_publisher
      @publisher = Publisher.find(params[:id])
    end

    def publisher_params
      params.require(:publisher).permit(:name, :description, :organization_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/press_releases_helper.rb
module PressReleasesHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PressReleaseManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: 'layouts/partials/header' %>
    <div class="container mt-5">
      <h2 class="mb-4">Featured Press Releases</h2>
      <div class="row">
        <%= yield %>
      </div>
    </div>
  <%#= render partial: 'layouts/partials/footer' %>
  </body>
  
</html>

app/views/layouts/partials/_admin_tabs.html.erb
<div class="admin-nav">
</div>

app/views/layouts/partials/_footer.html.erb
    <!-- Footer -->
<footer class="bg-light text-center text-lg-start mt-5">
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2024 Press Release Manager | <a class="text-dark" href="#">Privacy Policy</a>
  </div>
</footer>

app/views/layouts/partials/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'Press Release Manager', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: 'nav-link active' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Organizations', organizations_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Publishers', publishers_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Press Release', press_releases_path, class: 'nav-link' %>
        </li>
        <!-- Conditionally render admin links if the user is an admin -->
      </ul>
    </div>
    <div class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <span class="nav-link">Signed in as: <%= current_user.email %></span>
        </li>
        <li class="nav-item">
          <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'btn btn-outline-danger' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Log In', new_user_session_path, class: 'btn btn-outline-primary' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-outline-success' %>
        </li>
      <% end %>
    </div>
  </div>
</nav>

app/views/organizations/_form.html.erb
<%= form_with(model: organization, html: {class: "needs-validation", novalidate: true}) do |form| %>
  <% if organization.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h4 class="alert-heading"><%= pluralize(organization.errors.count, "error") %> prohibited this publisher from being saved:</h4>
      <ul>
        <% organization.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" + (organization.errors[:name].any? ? " is-invalid" : "") %>
    <% if organization.errors[:name].any? %>
      <div class="invalid-feedback">
        <%= organization.errors[:name].first %>
      </div>
    <% end %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" + (organization.errors[:description].any? ? " is-invalid" : "") %>
    <% if organization.errors[:description].any? %>
      <div class="invalid-feedback">
        <%= organization.errors[:description].first %>
      </div>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/organizations/_organization.html.erb
<div id="<%= dom_id(organization) %>" class="card">
  <div class="card-body">
    <h5 class="card-title">Organization Details</h5>
    <p class="card-text"><strong>Name:</strong> <%= organization.name %></p>
    <p class="card-text"><strong>Description:</strong> <%= organization.description %></p>
  </div>
</div>

app/views/organizations/edit.html.erb
<div class="container">
  <h1>Editing Organization</h1>

  <%= render "form", organization: @organization %>

  <div class="mt-3">
    <div class="row">
      <div class="col">
        <%= link_to "Back to Organizations", organizations_path, class: "btn btn-secondary" %>
      </div>
    </div>
  </div>

</div>

app/views/organizations/index.html.erb
<p class="text-success"><%= notice %></p>

<h1>Organizations <%= link_to "New organization", new_organization_path, class: "btn btn-success" %> </h1> 

<div id="organizations">
  <% @organizations.each do |organization| %>

    <div class="card mb-3">
      <div class="card-body">
        <%= render organization %>
      </div>
      <div class="card-footer">
        <%= link_to "Show this organization", organization, class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/organizations/new.html.erb
<div class="container">
  <h1>New Organization</h1>

  <%= render "form", organization: @organization %>

  <div class="mt-3">
    <div class="row">
      <div class="col">
        <%= link_to "Back to Organizations", organizations_path, class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
</div>

app/views/organizations/show.html.erb
<p class="text-success"><%= notice %></p>

<% if @organization.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <ul>
      <% @organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= render @organization %>

<div class="mt-5">
  <div class="row">
    <div class="col-2">
      <%= link_to "Edit this Organization", edit_organization_path(@organization), class: "btn btn-primary mr-2" %>
    </div>
    <div class="col">
      <%= button_to "Destroy this Organization", @organization, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
    </div>
  </div>
</div>

app/views/press_releases/_form.html.erb
<%= form_with(model: press_release, html: {class: "needs-validation", novalidate: true}) do |form| %>
  <% if press_release.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h4 class="alert-heading"><%= pluralize(press_release.errors.count, "error") %> prohibited this publisher from being saved:</h4>
      <ul>
        <% press_release.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" + (press_release.errors[:title].any? ? " is-invalid" : "") %>
    <% if press_release.errors[:title].any? %>
      <div class="invalid-feedback">
        <%= press_release.errors[:title].first %>
      </div>
    <% end %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :content %>
    <%= form.text_area :content, class: "form-control" + (press_release.errors[:content].any? ? " is-invalid" : "") %>
    <% if press_release.errors[:content].any? %>
      <div class="invalid-feedback">
        <%= press_release.errors[:content].first %>
      </div>
    <% end %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :publish_date, "Publish Date (should be at least 5 hours ahead of the current time)" %>
    <%= form.datetime_field :publish_date, class: "form-control" + (press_release.errors[:publish_date].any? ? " is-invalid" : ""), placeholder: "Select publish date", value: (Time.now + 5.hours).strftime('%Y-%m-%dT%H:%M'), min: (Time.now + 5.hours).strftime('%Y-%m-%dT%H:%M') %>
    <% if press_release.errors[:publish_date].any? %>
      <div class="invalid-feedback">
        <%= press_release.errors[:publish_date].first %>
      </div>
    <% end %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :status %>
    <% if press_release.new_record? %>
      <%= form.select :status, { "Draft" => "draft" }, {}, { class: "form-control" + (press_release.errors[:status].any? ? " is-invalid" : "") } %>
    <% else %>
      <% current_status = press_release.status %> <!-- Get the current status value -->
      <%= form.select :status, PressRelease.statuses.map { |key, value| [key.titleize, key] }, { selected: current_status }, { class: "form-control", readonly: true } %>
    <% end %>
    <% if press_release.errors[:status].any? %>
      <div class="invalid-feedback">
        <%= press_release.errors[:status].first %>
      </div>
    <% end %>
  </div>


  <div class="form-group mb-3">
    <%= form.label :publisher_id %>
    <%= form.collection_select :publisher_id, Publisher.all, :id, :name, {include_blank: "Choose publisher"}, class: "form-control" + (press_release.errors[:publisher_id].any? ? " is-invalid" : "") %>
    <% if press_release.errors[:publisher_id].any? %>
      <div class="invalid-feedback">
        <%= press_release.errors[:publisher_id].first %>
      </div>
    <% end %>
  </div>

  <!-- Hidden field for user_id -->
  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="form-group">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/press_releases/_press_release.html.erb
<div id="<%= dom_id(press_release) %>" class="card">
  <div class="card-body">
    <h5 class="card-title">Press Release Details</h5>
    <p class="card-text"><strong>Title:</strong> <%= press_release.title %></p>
    <p class="card-text"><strong>Content:</strong> <%= press_release.content %></p>
    <p class="card-text"><strong>Publish Date:</strong> <%= press_release.publish_date.strftime("%B %d, %Y %I:%M %p %Z") %></p>
    <p class="card-text"><strong>Status:</strong> <%= press_release.status %></p>
    <p class="card-text"><strong>Author:</strong> <%= press_release.author.email %></p>
    <p class="card-text"><strong>Publisher:</strong> <%= press_release.publisher.name %></p>

  </div>
</div>

app/views/press_releases/edit.html.erb
<div class="container">
  <h1>Editing Press Release</h1>

  <%= render "form", press_release: @press_release %>

  <div class="mt-3">
    <div class="row">
      <div class="col">
        <%= link_to "Back to press releases", press_releases_path, class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
</div>

app/views/press_releases/index.html.erb
<p class="text-success"><%= notice %></p>

<h1>Press Releases <%= link_to "New Press Release", new_press_release_path, class: "btn btn-success" %></h1>

<div class="tabs">
  <!-- Tab Links -->
  <ul class="nav nav-tabs" id="pressReleaseTabs" role="tablist">
    <li class="nav-item" role="presentation">
      <%= link_to 'Published', press_releases_path(status: 'published'), class: "nav-link active", data: { turbo_frame: "press_releases_list" } %>
    </li>
    <li class="nav-item" role="presentation">
      <%= link_to 'Draft', press_releases_path(status: 'draft'), class: "nav-link", data: { turbo_frame: "press_releases_list" } %>
    </li>
    <li class="nav-item" role="presentation">
      <%= link_to 'Archived', press_releases_path(status: 'archived'), class: "nav-link", data: { turbo_frame: "press_releases_list" } %>
    </li>
  </ul>

  <!-- Tab Content -->
  <%= turbo_frame_tag 'press_releases_list' do %>
    <div class="tab-content" id="pressReleaseTabsContent">
      <div class="tab-pane fade show active" role="tabpanel">
        <div class="row">
          <% if @press_releases.present? %>
            <% @press_releases.each do |press_release| %>
              <div class="col-md-4 mb-4">
                <%= render PressReleaseComponent.new(press_release: press_release) %>
              </div>
            <% end %>
          <% else %>
            <div class="alert alert-info" role="alert">
              <strong>No press releases found.</strong>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/press_releases/new.html.erb
<div class="container">
  <h1>New PressRelease</h1>

  <%= render "form", press_release: @press_release %>

  <div class="mt-3">
    <div class="row">
      <div class="col">
        <%= link_to "Back to publishers", press_releases_path, class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
</div>

app/views/press_releases/show.html.erb
<p class="text-success"><%= notice %></p>

<% if @press_release.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <ul>
      <% @press_release.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= render @press_release %>

<div class="mt-5">
  <div class="row">
    <div class="col-2">
      <%= link_to "Edit this press release", edit_press_release_path(@press_release), class: "btn btn-primary mr-2" %>
    </div>
    <div class="col">
      <%= button_to "Destroy this press release", @press_release, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
    </div>
  </div>
</div>

app/views/publishers/_form.html.erb
<%= form_with(model: publisher, html: {class: "needs-validation", novalidate: true}) do |form| %>
  <% if publisher.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h4 class="alert-heading"><%= pluralize(publisher.errors.count, "error") %> prohibited this publisher from being saved:</h4>
      <ul>
        <% publisher.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" + (publisher.errors[:name].any? ? " is-invalid" : "") %>
    <% if publisher.errors[:name].any? %>
      <div class="invalid-feedback">
        <%= publisher.errors[:name].first %>
      </div>
    <% end %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" + (publisher.errors[:description].any? ? " is-invalid" : "") %>
    <% if publisher.errors[:description].any? %>
      <div class="invalid-feedback">
        <%= publisher.errors[:description].first %>
      </div>
    <% end %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :organization_id, "Organization" %>
    <%= form.collection_select :organization_id, Organization.all, :id, :name, {prompt: "Choose an Organization"}, {class: "form-select" + (publisher.errors[:organization_id].any? ? " is-invalid" : "")} %>
    <% if publisher.errors[:organization_id].any? %>
      <div class="invalid-feedback">
        <%= publisher.errors[:organization_id].first %>
      </div>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/publishers/_publisher.html.erb
<div id="<%= dom_id(publisher) %>" class="card">
  <div class="card-body">
    <h5 class="card-title">Publisher Details</h5>
    <p class="card-text"><strong>Name:</strong> <%= publisher.name %></p>
    <p class="card-text"><strong>Description:</strong> <%= publisher.description %></p>
    <p class="card-text"><strong>Organization:</strong> <%= publisher.organization&.name %></p>
  </div>
</div>

app/views/publishers/edit.html.erb
<div class="container">

  <h1>Editing publisher</h1>
  <%= render "form", publisher: @publisher %>

  <div class="mt-3">
    <div class="row">
      <div class="col">
        <%= link_to "Back to publishers", publishers_path, class: "btn btn-secondary" %>
      </div>
    </div>
  </div>

</div>

app/views/publishers/index.html.erb
<p class="text-success"><%= notice %></p>

<h1>Publishers <%= link_to "New Publisher", new_publisher_path, class: "btn btn-success" %></h1>

<div id="publishers">
  <% @publishers.each do |publisher| %>
    <div class="card mb-3">
      <div class="card-body">
        <%= render publisher %>
      </div>
      <div class="card-footer">
        <%= link_to "Show this publisher", publisher, class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/publishers/new.html.erb
<div class="container">
  <h1>New publisher</h1>

  <%= render "form", publisher: @publisher %>

  <div class="mt-3">
    <div class="row">
      <div class="col">
        <%= link_to "Back to publishers", publishers_path, class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
</div>

app/views/publishers/show.html.erb
<p class="text-success"><%= notice %></p>

<% if @publisher.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <ul>
      <% @publisher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= render @publisher %>

<div class="mt-5">
  <div class="row">
    <div class="col-2">
      <%= link_to "Edit this publisher", edit_publisher_path(@publisher), class: "btn btn-primary mr-2" %>
    </div>
    <div class="col">
      <%= button_to "Destroy this publisher", @publisher, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
    </div>
  </div>
</div>